name: 'awesome-readme-generator'
description: 'Generate Awesome Readme.md from your Github starred repos ;)'
branding:
  icon: 'bookmark'
  color: 'yellow'
inputs:
  github-token:
    description: 'github token'
    required: true
  owner:
    description: 'owner name'
    required: true
  group-by:
    description: 'Group repos by language or topics.'
    default: 'language'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
